#ifndef COSTANTSETTINGS_HPP
#define COSTANTSETTINGS_HPP


#define POOL_SIZE 1
#define DIM_MULTI_LEVEL 150
#define N_POINTS_SLIDING_WINDOW 200
#define MAX_SPATIAL_INVARIANT_TRACK_ARRAY_LEN 300
#define WINDOW_SIZE 64

#endif // COSTANTSETTINGS_HPP



